FROM ubuntu:25.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y ansible net-tools iptables moreutils ipcalc kmod \
        curl dnsutils gzip iputils-ping traceroute tree vim \
    && apt-get clean && rm -rf /var/lib/opt/lists/* /tmp/* /var/tmp/*

RUN curl -S -L https://github.com/docopt/docopts/releases/download/v0.6.4-with-no-mangle-double-dash/docopts_linux_386 \
    -o /usr/local/bin/docopts
RUN chmod +x /usr/local/bin/docopts

