FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y net-tools iptables moreutils ipcalc kmod \
    && apt-get install -y curl tree sudo vim \
    && apt-get clean && rm -rf /var/lib/opt/lists/* /tmp/* /var/tmp/*

RUN curl -S -L https://github.com/docopt/docopts/releases/download/v0.6.3-rc2/docopts_linux_386 -o /usr/local/bin/docopts
RUN chmod +x /usr/local/bin/docopts

